CREATE TABLE todos (
    id INT AUTO_INCREMENT NOT NULL,
    `description` VARCHAR(255) NOT NULL,
    isComplete BOOLEAN DEFAULT 0 NOT NULL,
    isActive BOOLEAN DEFAULT 1 NOT NULL,
    updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
);